version: '3'

services:
#  node:
#    image: ritualnetwork/infernet-node-internal:1.0.0.5
#    ports:
#      - "0.0.0.0:4000:4000"
#    volumes:
#      - ./config.json:/app/config.json
#      - node-logs:/logs
#      - /var/run/docker.sock:/var/run/docker.sock
#    tty: true
#    networks:
#      - network
#    depends_on:
#      - redis
#      - anvil-node
#    restart:
#      on-failure
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    stop_grace_period: 1m
#    container_name: infernet-node

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    networks:
      - network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    restart:
      on-failure

  fluentbit:
    image: fluent/fluent-bit:latest
    expose:
      - "24224"
    environment:
      - FLUENTBIT_CONFIG_PATH=/fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log:ro
    networks:
      - network
    restart:
      on-failure

  anvil-node:
      image: ritualnetwork/infernet-anvil-internal:1.0.2
      command: --host 0.0.0.0 --port 3000 --load-state infernet_deployed.json -b 1
      ports:
        - "8545:3000"
      networks:
        - network
      container_name: anvil-node

networks:
  network:

volumes:
  node-logs:
  redis-data:
